import React, { useState, useEffect } from 'react';
import { CalendarClock, AlertTriangle, Download, CalendarDays, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function DeadlineTracker() {
    const [formData, setFormData] = useState({
        filing_date: new Date().toISOString().split('T')[0],
        service_date: '',
        basis: 'filing_date',
        suit_type: 'civil',
        case_type: 'Original Suit'
    });
    const [error, setError] = useState(null);
    const [timelines, setTimelines] = useState([]);

    const isOriginalSuit = formData.case_type === 'Original Suit';

    useEffect(() => {
        if (isOriginalSuit && formData.basis !== 'service_date') {
            setFormData(prev => ({ ...prev, basis: 'service_date' }));
        }
    }, [isOriginalSuit, formData.basis]);

    const addDays = (date, days) => {
        const result = new Date(date);
        result.setDate(result.getDate() + days);
        return result;
    };

    const getDaysRemaining = (deadline) => {
        const today = new Date();
        const diffTime = deadline - today;
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
        return diffDays;
    };

    const handleCalculate = () => {
        if (formData.case_type !== 'Original Suit') {
            setError('Deadlines for this case type are coming soon.');
            return;
        }
        if (!formData.service_date) {
            setError('Please enter the service of summons date.');
            return;
        }

        setError(null);
        setTimelines([]);

        const service = new Date(formData.service_date);
        if (Number.isNaN(service.getTime())) {
            setError('Invalid service of summons date.');
            return;
        }

        const maxDays = formData.suit_type === 'commercial' ? 120 : 90;
        const standardDeadline = addDays(service, 30);
        const maxDeadline = addDays(service, maxDays);

        const computed = [
            {
                title: 'Written Statement (standard)',
                dueDate: standardDeadline,
                days: getDaysRemaining(standardDeadline),
                source: 'Order VIII Rule 1 CPC (trigger: service of summons)'
            },
            {
                title: 'Written Statement (max)',
                dueDate: maxDeadline,
                days: getDaysRemaining(maxDeadline),
                source: formData.suit_type === 'commercial'
                    ? 'Commercial Courts Act, 2015 read with Order VIII Rule 1 CPC (Commercial) (strict 120 days max)'
                    : 'CPC (extendable up to 90 days max)'
            },
        ];

        setTimelines(computed);
    };

    const downloadICal = () => {
        if (!timelines.length) return;
        const baseDate = formData.service_date || formData.filing_date;
        let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Lumina Copilot//EN\n";
        
        timelines.forEach(d => {
            const isoDate = d.dueDate.toISOString().split('T')[0];
            const dateStr = isoDate.replace(/-/g, '') + "T090000Z";
            icsContent += "BEGIN:VEVENT\n";
            icsContent += `DTSTART:${dateStr}\n`;
            icsContent += `DTEND:${dateStr}\n`;
            icsContent += `SUMMARY:Deadline: ${d.title}\n`;
            icsContent += `DESCRIPTION:Source: ${d.source}. Generated by Lumina Copilot.\n`;
            icsContent += "END:VEVENT\n";
        });
        
        icsContent += "END:VCALENDAR";
        
        const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
        const link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        link.setAttribute('download', `Deadlines_${baseDate}.ics`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="max-w-5xl mx-auto py-12 px-6">
            <h1 className="text-3xl font-black mb-8 flex items-center gap-3"><CalendarClock className="text-indigo-600" /> Deadline Tracker</h1>
            
            <div className="bg-white rounded-2xl p-6 border shadow-sm mb-8 flex flex-col gap-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-end">
                    <div className="w-full">
                        <label className="block text-sm font-bold mb-2">Trigger Basis</label>
                        <select
                            className="w-full p-3 border rounded-xl"
                            value={isOriginalSuit ? 'service_date' : formData.basis}
                            onChange={e => setFormData({...formData, basis: e.target.value})}
                            disabled={isOriginalSuit}
                        >
                            <option value="filing_date">Filing date</option>
                            <option value="service_date">Service of summons date</option>
                        </select>
                        {isOriginalSuit && (
                            <div className="text-xs font-bold text-slate-500 mt-2">
                                For Original Suit, written statement timelines must be calculated from the service of summons date.
                            </div>
                        )}
                    </div>
                    <div className="w-full">
                        <label className="block text-sm font-bold mb-2">Filing Date</label>
                        <input type="date" className="w-full p-3 border rounded-xl" value={formData.filing_date} onChange={e => setFormData({...formData, filing_date: e.target.value})} />
                    </div>
                    <div className="w-full">
                        <label className="block text-sm font-bold mb-2">Service of Summons Date</label>
                        <input type="date" className="w-full p-3 border rounded-xl" value={formData.service_date} onChange={e => setFormData({...formData, service_date: e.target.value})} />
                    </div>
                    {isOriginalSuit && (
                        <div className="w-full">
                            <label className="block text-sm font-bold mb-2">Suit Type</label>
                            <select className="w-full p-3 border rounded-xl" value={formData.suit_type} onChange={e => setFormData({...formData, suit_type: e.target.value})}>
                                <option value="civil">Normal Civil (CPC)</option>
                                <option value="commercial">Commercial</option>
                            </select>
                        </div>
                    )}
                    <div className="w-full">
                        <label className="block text-sm font-bold mb-2">Case Type</label>
                        <select className="w-full p-3 border rounded-xl" value={formData.case_type} onChange={e => setFormData({...formData, case_type: e.target.value})}>
                            <option>Original Suit</option>
                            <option disabled>Execution (Coming Soon)</option>
                            <option disabled>Appeal (Coming Soon)</option>
                            <option disabled>Arbitration (Coming Soon)</option>
                        </select>
                    </div>
                </div>
                <button onClick={handleCalculate} className="py-3 px-8 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl flex items-center justify-center gap-2 transition md:w-auto w-full disabled:opacity-50 h-[50px]">
                    Calculate Deadlines
                </button>
            </div>

            {error && <div className="text-rose-600 text-sm bg-rose-50 p-4 rounded-xl flex items-center gap-2 mb-8"><AlertTriangle/>{error}</div>}

            <AnimatePresence mode="wait">
                {timelines.length > 0 ? (
                    <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} className="bg-white border rounded-2xl shadow-sm overflow-hidden">
                        <div className="p-6 border-b flex justify-between items-center bg-slate-50">
                            <div>
                                <h2 className="text-xl font-bold flex items-center gap-2"><CalendarDays className="text-indigo-600"/> Computed Timelines</h2>
                                <div className="text-xs font-bold text-slate-500 mt-1">
                                    Basis: service of summons date | Base date: {formData.service_date}
                                </div>
                            </div>
                            <button onClick={downloadICal} className="flex items-center gap-2 px-4 py-2 bg-white border rounded-lg text-sm font-bold shadow-sm hover:bg-slate-50">
                                <Download size={16} /> Export .iCal
                            </button>
                        </div>
                        <div className="p-6 space-y-4">
                            {timelines.map((d, i) => (
                                <div key={i} className="flex flex-col md:flex-row md:items-center justify-between p-4 border rounded-xl hover:shadow-md transition bg-white gap-4 relative overflow-hidden">
                                    <div className={`absolute left-0 top-0 bottom-0 w-1 ${d.days < 7 ? 'bg-rose-500' : d.days < 21 ? 'bg-amber-500' : 'bg-emerald-500'}`} />
                                    <div className="pl-2">
                                        <h3 className="text-lg font-bold text-slate-800">{d.title}</h3>
                                        <p className="text-sm text-slate-500 mt-1 cursor-help group" title="Legal Source">
                                            {d.source}
                                        </p>
                                    </div>
                                    <div className="flex items-center gap-6 md:justify-end">
                                        <div className="text-right">
                                            <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Due Date</div>
                                            <div className="text-[15px] font-black">{d.dueDate.toISOString().split('T')[0]}</div>
                                        </div>
                                        <div className={`px-4 py-2 rounded-lg text-sm font-bold text-center min-w-[100px] ${
                                            d.days < 7 ? 'bg-rose-100 text-rose-700' : 
                                            d.days < 21 ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'
                                        }`}>
                                            {d.days < 0 ? 'Expired' : `${d.days} Days`}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </motion.div>
                ) : (
                    <div className="h-full min-h-[400px] flex flex-col items-center justify-center bg-nyaya-surface/30 border-2 border-dashed border-nyaya-border rounded-[2rem] text-center p-12">
                        <div className="w-16 h-16 bg-white border border-nyaya-border rounded-2xl flex items-center justify-center mb-6 shadow-sm text-nyaya-muted/40">
                            <CalendarClock size={32} />
                        </div>
                        <h3 className="text-xl font-bold text-nyaya-text mb-2">Automated Compliance</h3>
                        <p className="text-nyaya-muted max-w-sm leading-relaxed">
                            Select a filing date and case type above to calculate deadlines.
                        </p>
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
}
